export const provinceMap: Record<string, { name: string; slug: string }> = {
  "ES-C": { name: "A Coruña", slug: "a-coruna" },
  "ES-VI": { name: "Álava", slug: "alava" },
  "ES-AB": { name: "Albacete", slug: "albacete" },
  "ES-A": { name: "Alicante", slug: "alicante" },
  "ES-AL": { name: "Almería", slug: "almeria" },
  "ES-O": { name: "Asturias", slug: "asturias" },
  "ES-AV": { name: "Ávila", slug: "avila" },
  "ES-BA": { name: "Badajoz", slug: "badajoz" },
  "ES-PM": { name: "Illes Balears", slug: "illes-balears" },
  "ES-B": { name: "Barcelona", slug: "barcelona" },
  "ES-BU": { name: "Burgos", slug: "burgos" },
  "ES-CC": { name: "Cáceres", slug: "caceres" },
  "ES-CA": { name: "Cádiz", slug: "cadiz" },
  "ES-S": { name: "Cantabria", slug: "cantabria" },
  "ES-CS": { name: "Castellón", slug: "castellon" },
  "ES-CR": { name: "Ciudad Real", slug: "ciudad-real" },
  "ES-CO": { name: "Córdoba", slug: "cordoba" },
  "ES-CU": { name: "Cuenca", slug: "cuenca" },
  "ES-GI": { name: "Girona", slug: "girona" },
  "ES-GR": { name: "Granada", slug: "granada" },
  "ES-GU": { name: "Guadalajara", slug: "guadalajara" },
  "ES-SS": { name: "Guipúzcoa", slug: "guipuzcoa" },
  "ES-H": { name: "Huelva", slug: "huelva" },
  "ES-HU": { name: "Huesca", slug: "huesca" },
  "ES-J": { name: "Jaén", slug: "jaen" },
  "ES-LO": { name: "La Rioja", slug: "la-rioja" },
  "ES-GC": { name: "Las Palmas", slug: "las-palmas" },
  "ES-LE": { name: "León", slug: "leon" },
  "ES-L": { name: "Lleida", slug: "lleida" },
  "ES-LU": { name: "Lugo", slug: "lugo" },
  "ES-M": { name: "Madrid", slug: "madrid" },
  "ES-MA": { name: "Málaga", slug: "malaga" },
  "ES-MU": { name: "Murcia", slug: "murcia" },
  "ES-NA": { name: "Navarra", slug: "navarra" },
  "ES-OR": { name: "Ourense", slug: "ourense" },
  "ES-P": { name: "Palencia", slug: "palencia" },
  "ES-PO": { name: "Pontevedra", slug: "pontevedra" },
  "ES-SA": { name: "Salamanca", slug: "salamanca" },
  "ES-TF": { name: "Santa Cruz de Tenerife", slug: "santa-cruz-de-tenerife" },
  "ES-SG": { name: "Segovia", slug: "segovia" },
  "ES-SE": { name: "Sevilla", slug: "sevilla" },
  "ES-SO": { name: "Soria", slug: "soria" },
  "ES-T": { name: "Tarragona", slug: "tarragona" },
  "ES-TE": { name: "Teruel", slug: "teruel" },
  "ES-TO": { name: "Toledo", slug: "toledo" },
  "ES-V": { name: "Valencia", slug: "valencia" },
  "ES-VA": { name: "Valladolid", slug: "valladolid" },
  "ES-BI": { name: "Vizcaya", slug: "vizcaya" },
  "ES-ZA": { name: "Zamora", slug: "zamora" },
  "ES-Z": { name: "Zaragoza", slug: "zaragoza" },
};